name: recipe_finder
description: "A Flutter app that allows users to input ingredients and fetch matching recipes from the Spoonacular API."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - .env
